name: Build and Deploy Hugo Blog

on:
  workflow_run:
    workflows:
      - Translate Content
    types:
      - completed
  workflow_dispatch:

jobs:
  build-deploy:
    if: >
      github.event_name != 'workflow_run' ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_commit.message != 'chore(post): update translated content'
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.140.1'
          extended: true

      - name: Build Hugo site
        run: hugo --gc --minify

      - name: Deploy to blogWeb repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: yexca/blog-web
          publish_branch: main  # blogWeb 的分支
          publish_dir: ./public  # Hugo 默认输出目录
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
